const uploadConstants = {
  UPLOAD_STORE: 'UPLOAD_STORE',
  UPLOAD_REQUEST: 'UPLOAD_REQUEST',
  UPLOAD_SUCCESS: 'UPLOAD_SUCCESS',
  UPLOAD_FAILURE: 'UPLOAD_FAILURE',
  UPLOAD_CLEAR: 'UPLOAD_CLEAR',
};

export default uploadConstants;
